version: '3.3'
services:
  db:
    image: library/mysql:5.7
    restart: always
    container_name: cardsagainsthumanity_db
    environment:
      MYSQL_ROOT_PASSWORD: 'cah_db_user@#!'
    ports:
      - 3306:3306
    volumes:
      - ../data:/var/lib/mysql
